name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    services:
      dynamo:
        image: amazon/dynamodb-local
        ports:
          - "8000:8000"
    env:
      DYNAMO_ENDPOINT: "http://localhost:8000"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 setuptools
        pip install .
    - name: Run Tests
      run: |
        python setup.py test
